### ISSUE TITLE
DPL-679-1 - Check if endpoint should be deprecated

### ISSUE THREAD

**Issue by emrojo** [sanger/event_warehouse#18]
The consumers leave some endpoints available to create events from an hypothetical http server. We should check if this is needed still.

**Comment by JamesGlover** [comment]
Where do you mean? 

Develop does have the beginnings of a http server which was intended for an API, but I don't *think* this has any create actions enabled. (This probably needs to be revisited. I went back to it shortly before paternity leave and some of the gems we were going to use have been abandoned) Is there another server somewhere?

**Comment by BenTopping** [comment]
Closing as in Done.
