### ISSUE TITLE
DPL-1115 Archive TAT-WOW queries

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/event_warehouse#457]
**Describe the Housekeeping**
Find a place to archive the queries written for the TAT-WOW project so that they are available if we want to refer back to them in future. They are currently in these two branches:
- https://github.com/sanger/event_warehouse/tree/DPL-530-TAT-WOW-LCMB-ISC
- https://github.com/sanger/event_warehouse/tree/235-dpl-578-data-extracts

See closed PRs for the diff:
- https://github.com/sanger/event_warehouse/pull/314
- https://github.com/sanger/event_warehouse/pull/424

Keeping them in these branches is not a good long term solution as we want to keep our repos clean.

**Comment by yoldas** [comment]
I think we can do something like this to preserve the commit history
- create a new repo for the tat-wow
- move folders from branches to the new repo by applying a git director filter
- move the new repo to archive

**Comment by seenanair** [comment]
Notes:-

Task - Move ‘queries’ folder from branches  DPL-530-TAT-WOW-LCMB-ISC, 235-dpl-578-data-extracts to a new repo with commit history
(https://github.com/sanger/event_warehouse/tree/DPL-530-TAT-WOW-LCMB-ISC)(https://github.com/sanger/event_warehouse/tree/235-dpl-578-data-extracts)

Method:-

I've used git-filter-repo utility 

1. pip install git-filter-repo
2. Create a repo called tat-wow-queries-backup
3. For merging branches in event_warehouse repo
    * Create branch TAT-WOW-merge-queries from   [DPL-530-TAT-WOW-LCMB-ISC](https://github.com/sanger/event_warehouse/tree/DPL-530-TAT-WOW-LCMB-ISC)
    *  Merge branch [235-dpl-578-data-extracts](https://github.com/sanger/event_warehouse/tree/235-dpl-578-data-extracts) to  TAT-WOW-merge-queries
4. Create a fresh clone of event_warehouse by git clone <event_warehouse.git> event_warehouse
5.  In the event_warehouse directory
    * git remote rm origin
    * git filter-repo --path queries --force 
6. Create a fresh clone of  tat-wow-queries-backup
7.  In tat-wow-queries-backup directory
    * git remote add event_warehouse <path_to_event_warehouse_directory_path>
    * git fetch event_warehouse  (which shows an output as follows)
    * git branch event_warehouse remotes/event_warehouse/TAT-WOW-merge-queries (Now  in the new repo branch 'event_warehouse' set up to track 'event_warehouse/TAT-WOW-merge-queries’)
    * git merge event_warehouse --allow-unrelated-histories (if asked for message :quit and Press Enter)
    * git remote rm event_warehouse
    * git branch -d event_warehouse
    * git push origin main
